image: condaforge/mambaforge:22.9.0-1
tasks:
- name: configure conda env
  command: |
    mamba create --yes --quiet --name ntsynt
    conda activate ntsynt
    mamba install -c conda-forge -c bioconda --yes ntsynt
    cd /workspace
vscode:
  extensions:
    - anwar.papyrus-pdf

workspaceLocation: "/workspace"