image: condaforge/mambaforge:22.9.0-1
tasks:
- name: configure conda env
  init: |
      mamba create --yes --quiet --name ntsynt
      conda activate ntsynt
      mamba install -c conda-forge -c bioconda --yes ntsynt
- name: git clone
  command: |
    cd /workspace
    conda activate ntsynt
vscode:
  extensions:
    - anwar.papyrus-pdf

workspaceLocation: "/workspace"