# ntSynt CI

jobs:
- job:
  displayName: ubuntu-latest
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self
    persistCredentials: true
    submodules: true

  - script: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - script: conda create --yes --quiet --name ntsynt_ci
    displayName: Create Anaconda environment

  - script: |
      source activate ntsynt_ci
      conda install --yes -c bioconda -c conda-forge python mamba
      mamba install --yes -c bioconda -c conda-forge intervaltree pybedtools ncls python-igraph compilers btllib meson ninja snakemake samtools pytest seqtk pylint
    displayName: Install dependencies

  - script: |
      source activate ntsynt_ci
      meson setup build --prefix=$(pwd)/ntSynt_build
      cd build
      ninja install
    displayName: Install ntSynt

  - script: |
      source activate ntsynt_ci
      cd ntSynt_build/bin/
      pylint --rcfile ../../bin/.pylintrc --extension-pkg-allow-list=btllib *py
    displayName: Run pylint

  - script: |
      source activate ntsynt_ci
      ./ntSynt_build/bin/ntSynt --help
    displayName: Print ntSynt help message

  - script: |
      source activate ntsynt_ci
      export PATH=$(pwd)/ntSynt_build/bin:$PATH
      cd tests
      pytest -vs ntsynt_tests.py
    displayName: Run pytests

- job:
  displayName: macOS-latest
  pool:
    vmImage: 'macOS-latest'

  steps:
  - checkout: self
    persistCredentials: true
    submodules: true

  - script: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - script: conda create --yes --quiet --name ntsynt_ci
    displayName: Create Anaconda environment

  - script: |
      source activate ntsynt_ci
      conda install --yes -c bioconda -c conda-forge python mamba
      mamba install --yes -c bioconda -c conda-forge intervaltree pybedtools ncls python-igraph compilers  btllib meson ninja snakemake samtools pytest seqtk
    displayName: Install dependencies

  - script: |
      source activate ntsynt_ci
      meson setup build --prefix=$(pwd)/ntSynt_build
      cd build
      ninja install
    displayName: Install ntSynt

  - script: |
      source activate ntsynt_ci
      ./ntSynt_build/bin/ntSynt --help
    displayName: Print ntSynt help message

  - script: |
      source activate ntsynt_ci
      export PATH=$(pwd)/ntSynt_build/bin:$PATH
      cd tests
      pytest -vs ntsynt_tests.py
    displayName: Run pytests
