# ntSynt CI

jobs:
- job:
  displayName: ubuntu-latest
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self
    persistCredentials: true
    submodules: true

  - script: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - script: conda create --yes --quiet --name ntsynt_ci
    displayName: Create Anaconda environment

  - script: |
      source activate ntsynt_ci
      conda install --yes --name ntsynt_ci -c bioconda -c conda-forge python conda-libmamba-solver
      conda install --yes -c bioconda -c conda-forge --solver=libmamba python intervaltree pybedtools ncls python-igraph compilers btllib meson ninja snakemake samtools
    displayName: Install dependencies

  - script: |
      source activate ntsynt_ci
      meson build --prefix=$(pwd)/ntSynt_build
      cd build
      ninja install
    displayName: Install ntSynt

  - script: |
      source activate ntsynt_ci
      ./ntSynt_build/bin/ntSynt.py --help
    displayName: Test ntSynt (help message)

